# Generated by Django 5.2.5 on 2025-08-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='enderco',
            new_name='endereco',
        ),
    ]
